### ISSUE TITLE
Problem with CS:GO Server

### ISSUE THREAD

**Issue by snstalev** [dgibbs64/linuxgsm#402]
So i am running a dedicated CSGO server with your script and until the last update i had no problems, it was running perfect. After the update, something happened and i can't seem to find the exact same problem anywhere on the web.

Here is the problem. I run the server under Linux and when i start the server everything is normal as always. My server pops up on the public internet tab in valve's servers and i can also see it and connect to it. And here is the problem! When i connect, it goes to black screen with the following messages:

Connecting to public(xxx.xxx.xxx.xxx:27015) ... Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff Connecting to public(xxx.xxx.xxx.xxx:27015) ... Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff Retrying public(xxx.xxx.xxx.xxx:27015) Retrying public(xxx.xxx.xxx.xxx:27015) Retrying public(xxx.xxx.xxx.xxx:27015)

.. it retries 3 times and then from black screen, goes to the original loading screen background and does the same thing again. When it reaches 3 retries, it goes again to black screen and so on.

Do you have any idea what is going on?

Thanks in advance!

**Comment by marcelotk15** [comment]
Yeah, i try the same problem.
But is the sourcemod. Because a install the metamod and the server run normal, after i install the source mod boom, a go have the same problem you having.

**Comment by xMqt** [comment]
Are you using the last snapshots from sourcemod/metamod?

**Comment by marcelotk15** [comment]
I fix my problem.

First: Deteting the sourcemod.vdf file in addons/metamod
Second: add this "addons/sourcemod/bin/sourcemod_mm" line in metaplugins.ini of addons/metamod. 

Work fine now for me.

**Comment by snstalev** [comment]
I'll try it now.

**Comment by snstalev** [comment]
Ok. It really seems that the problem is the sourcemod. When i renamed the addons folder, everything worked. I installed the newest snapshot of sourcemod but the problem persists. I also did what marcelotk15 said and still didnt worked. When i check the logs this is the only sourcemod/metamod related thing i get

L 05/25/2015 - 12:00:30: [META] Could not open folder "/home/progamesgo/serverfiles/csgo/#R÷Ðòl" (No such file or directory)
L 05/25/2015 - 12:00:30: [META] Loaded 0 plugins.

**Comment by xMqt** [comment]
I was having exactly the same problem. Can you please:

- Delete METAMOD & SOURCEMOD in /addons
- Delete SOURCEMOD in /cfg
- Download the last SNAPSHOTS version of both Metamod & Sourcemod. DO NOT DOWNLOAD THE NORMAL VERSION.

**Comment by xMqt** [comment]
http://www.metamodsource.net/snapshots

https://www.sourcemod.net/snapshots.php

**Comment by snstalev** [comment]
Just installing the newest metamod snapshot fixed the problem. Thanks a lot, i was struggling with this problem for like 10 days now. Cheers.

**Comment by iamdual** [comment]
I finally fixed. Problem solved with this steps;
- Install metamod & sourcemod's stable spanshots
- Remove sourcemod.vdf file from /addons/metamod/
- Open metaplugins.ini and add this: sm addons/sourcemod/bin/sourcemod_mm
- Set chmod 755 all server files

Thanks to @xMqt and @marcelotk15.

**Comment by Valkatastz** [comment]
These steps didn't solve my problem with the same error message " Server using 'public' lobbies, requiring pw no, lobby id ffffffffffffffff ". I've do step by step everything but still having this annoying headache.....

**Comment by DJPlaya** [comment]
Nice update Volvo, now ive got this Problem too
